version: "3"
services:
  ubuntu-texlive-ja:
    image: tanuking551/cytex-texlive:latest
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"
