version: "3"
services:
  ubuntu-texlive-ja:
    image: ran350/cytex-texlive:0.0.1
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"
